### ISSUE TITLE
xed build failure with python 3.x

### ISSUE THREAD

**Issue by mwkrentel** [intelxed/xed#109]
I'm seeing a problem building XED with Python 3.x, depending on where
I put the mbuild directory.

This is with the latest xed (bd73bdb2ee from Jan 29) and latest mbuild
(bb9123152a from Nov 27).  I clone xed, then cd into xed and clone
mbuild, so mbuild is a subdir of xed.

With python 2.7, this works (with mbuild a subdir of xed), but with
python 3.6.3, I get:

$ ./mfile.py 
module 'mbuild' has no attribute 'check_python_version'

But if I move the xed and mbuild directories to be side by side, then
it works with 2.7 and 3.6.3.

Strangely, with python 3.1.5, it fails in a different way with both
directory layouts (fails as subdir and side-by-side).

$ ./mfile.py 
[INVOKED] ./mfile.py
...
[PYTHON VERSION] 3.1.5
'_io.FileIO' object has no attribute 'read1'

----------

So, first let me check, is mbuild as a subidr of xed supposed to be
supported?  Is python 3.x supported?

The reason I ask is that I've written a spack recipe for xed.  (Are
you familiar with the spack package manager from Livermore?)  Spack is
sometimes a bit rigid in their way of doing things.  In this case,
they don't handle the case of multiple tar files or multiple git
clones very easily.

With spack, I can easily clone mbuild inside xed, but putting them
side-by-side is tougher.  Maybe I just got lucky that it worked as a
subdir with 2.7.

So, I'm looking for guidance ...  is it easier to fix xed to work with
Python 3.x as a subdir, or is it easier to push on spack to fix their
directory structure.

I'm hoping this will be a short fix for xed, but if I'm pushing the
bounds of what mbuild supports, then I apologize.  :-)

And btw, whatever the answer for the directory layout is, thanks very,
very much for making XED available on github!!  This simplifies my
work life somewhat.

Thanks,

--Mark Krentel

**Comment by markcharney** [comment]
Well, python 3.1 is kinda old (3.1 is from 2009.. although I don't know when the 3.1.9 release was made) and I am not able to support something that old.  We test with python 2.7.x and 3.x -- For 3.x, using  whatever the latest version of 3.x is on appveyor (3.5.x) and travis (3.4.x) at the moment.   I personally am using python 3.6 for my development machine.

I have never tried to build with mbuild as a subdir (instead of a sibling directory) to the xed directory. I can try and see. Shouldn't be a big deal, I think.

**Comment by markcharney** [comment]
You need to set the PYTHONPATH to the mbuild subdir of mbuild, if you know what I mean. Try this:

```
setenv PYTHONPATH `pwd`/mbuild
python3 ./mfile.py examples
```

worked for me :-)

**Comment by markcharney** [comment]
I'll add a check for python 3.4 or later, when using python 3.  Although some version between 3.1.9 and 3.3._whatever-is-last_ might work, I don't have them around for testing.

**Comment by mwkrentel** [comment]
Ok, that worked for me too.  Except that you set PYTHONPATH to the
root of the mbuild tree, not the mbuild subdir of mbuild.

I'm guessing that I could clone mbuild anywhere as long as I have
PYTHONPATH set accordingly.

I'll update my spack recipe to export PYTHONPATH.

Btw, I suggest that it's worth looking into spack (github.com/spack)
for package management, if you're not already familiar with it.  The
DOE labs for Exascale are moving this way.  In this case, I built
python 2.7.14, 3.1.5 and 3.6.3 for testing and it was pretty easy.

Thanks, that was easy!
All done!

--Mark

**Comment by markcharney** [comment]
great. I will look at spack.
